name: object-detection-env
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.8
  - opencv
  - matplotlib
  - pytorch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pillow
  - cudatoolkit=11.7 
  - transformers
